<?php
return [
    [
        "name" => "Appartamento di lusso",
        "type" => "Appartamento",
        "description" => "Un appartamento di lusso nel centro della città.",
        "night_price" => 200,
        "total_bath" => 3,
        "total_rooms" => 4,
        "total_beds" => 6,
        "mq" => 180,
        "photo" => "appartamento_lusso.jpg",
        "is_published" => true,
    ],
    [
        "name" => "Appartamento vista mare",
        "type" => "Appartamento",
        "description" => "Un accogliente appartamento con vista panoramica sul mare.",
        "night_price" => 150,
        "total_bath" => 2,
        "total_rooms" => 3,
        "total_beds" => 4,
        "mq" => 120,
        "photo" => "appartamento_vista_mare.jpg",
        "is_published" => true,
    ],
    [
        "name" => "Appartamento in montagna",
        "type" => "Appartamento",
        "description" => "Un appartamento accogliente nelle montagne.",
        "night_price" => 120,
        "total_bath" => 2,
        "total_rooms" => 2,
        "total_beds" => 3,
        "mq" => 90,
        "photo" => "appartamento_montagna.jpg",
        "is_published" => true,
    ],
    [
        "name" => "Appartamento moderno",
        "type" => "Appartamento",
        "description" => "Un appartamento moderno e ben arredato.",
        "night_price" => 180,
        "total_bath" => 2,
        "total_rooms" => 3,
        "total_beds" => 5,
        "mq" => 150,
        "photo" => "appartamento_moderno.jpg",
        "is_published" => true,
    ],
    [
        "name" => "Appartamento rustico",
        "type" => "Appartamento",
        "description" => "Un appartamento rustico con vista sulla campagna.",
        "night_price" => 100,
        "total_bath" => 1,
        "total_rooms" => 2,
        "total_beds" => 4,
        "mq" => 110,
        "photo" => "appartamento_rustico.jpg",
        "is_published" => true,
    ],
];
